const SPRITE = {
    KNIGHT: 0,
    ENEMY: 1,
    BACKGROUND: 2,
};

const RULES = {
    ENEMY_LIMIT: 3,
    NUMBER_OF_TILES: 20,
    TILE_SIZE: 64,
    EQUIPMENT_PANEL_PADDING_SIZE: 20,
    EQUIPMENT_PANEL_SIZE: 335,
};